const mongoose = require("mongoose");
const db = require("../models");

mongoose.connect(
  process.env.MONGODB_URI ||
  "mongodb://localhost/onedayindenver"
);

const eventSeed = [
    {
    name: "Roxburough State Park",
    catagory: "Adventure",
    rating: 3.0,
    time: 2.5,
    drive: 30,
    address: "4751 Roxborough Dr, Littleton, CO 80125",
    lat: 39.585202,
    long: -105.008655,
    attributes: ["Hiking", "Nature", "Pictures"],
    url: "http://cpw.state.co.us/placestogo/parks/Roxborough",
    description: "Beautiful hikes filled with dramatic red-rock formations.",
    advice: "If you are short on time, just hike up to Lyons Overlook Trial!",
    img: "https://image.ibb.co/eMkAhf/roxburough.jpg",
    start: new Date().toISOString().slice(0, 10)+"T10:30:00",
    time: "10:30:00"
},
{
    name: "Waterton Canyon",
    catagory: "Adventure",
    rating: 3.0,
    time: 3.0,
    drive: 30,
    address: "11300 Waterton Road Littleton, CO 80125",
    lat: 39.585202,
    long: -105.008655,
    attributes: ["Hiking", "Nature", "Pictures"],
    url: "http://www.coloradotrail.org/waterton.html",
    description: "6-mile of beautiful canyon open to hike, bike and horse.",
    advice: "Walk across the road to get to the trail head",
    img: "https://image.ibb.co/gW9E8L/Waterton-Cayon.jpg",
    start: new Date().toISOString().slice(0, 10)+"T10:30:00",
    time: "10:30:00"
},
{
    name: "Chatfield State Park",
    catagory: "Adventure",
    rating: 2.5,
    time: 2.5,
    drive: 30,
    address: "11500 N Roxborough Park Rd, Littleton, CO 80125",
    lat: 39.585202,
    long: -105.008655,
    attributes: ["Hiking", "Nature", "Water",],
    url: "http://cpw.state.co.us/placestogo/parks/Chatfield",
    description: "Float your boat in the lake, bicycle or hike in the foothills.",
    advice: "Chatfield has an amazing dog park for your furry friend!",
    img: "https://image.ibb.co/gAAza0/chatsfield.jpg",
    start: new Date().toISOString().slice(0, 10)+"T10:30:00",
    time: "10:30:00"
},
{
    name: "Look Out Mountain",
    catagory: "Adventure",
    rating: 4.0,
    time: 2.5,
    drive: 30,
    address: "987 Lookout Mountain Rd, Golden, CO 80401",
    lat: 39.741926,
    long: -105.228356,
    attributes: ["Hiking", "Nature", "Pictures"],
    url: "https://www.visitgolden.com/places-to-go/lookout-mountain/",
    description: "Excellent mountain vies 12 miles west of downtown Denver",
    advice: "hiking? Search for look out mountain trials.",
    img: "https://image.ibb.co/dqPsv0/lookout.jpg",
    start: new Date().toISOString().slice(0, 10)+"T10:30:00",
    time: "10:30:00"
},
{
    name: "N Table Mountain Trail",
    catagory: "Adventure",
    rating: 3.75,
    time: 2.5,
    drive: 30,
    address: "4788 CO-93, Golden, CO 80403",
    lat: 39.778943,
    long: -105.231783,
    attributes: ["Hiking", "Nature", "Pictures"],
    url: "https://www.cityofgolden.net/play/recreation-attractions/trails/north-table-mountain-trail/",
    description: "Short hike to a Great look out over Golden, CO.",
    advice: "The inital ascent is HARD, but the views are worth the effort!",
    img: "https://image.ibb.co/hU1STL/tabletop.jpg",
    start: new Date().toISOString().slice(0, 10)+"T10:30:00",
    time: "10:30:00"
},
{
    name: "Black Hawk Casinos",
    catagory: "Entertainment",
    rating: 4.00,
    time: 5,
    drive: 60,
    address: "132 Lawrence St, Central City, CO 80427",
    lat: 39.800791,
    long: -105.511258,
    attributes: ["Drinking", "Night Life", "Gambling"],
    url: "https://www.cityofblackhawk.org/",
    description: "Colorado’s gaming powerhouse pushing to become resort destination!",
    advice: "Try your luck! Have a blast!",
    img: "https://image.ibb.co/khHqhf/blackhawk.jpg",
    start: new Date().toISOString().slice(0, 10)+"T18:30:00",
    time: "18:30:00"
},
{
    name: "Blake Street",
    catagory: "Entertainment",
    rating: 4.00,
    time: 2,
    drive: 5,
    address: "1909 Blake St, Denver, CO 80202",
    lat: 39.753681,
    long: -104.995415,
    attributes: ["Drinking", "Night Life", "Party"],
    url: "http://www.haytersandco.com/",
    description: "Heart of Denver's night life. Explore many bars and clubs near Coors Field",
    advice: "It is call BroDo for a reason.",
    img: "https://image.ibb.co/m1z32f/blake.jpg",
    start: new Date().toISOString().slice(0, 10)+"T19:30:00",
    time: "19:30:00"
},
{
    name: "16th Street Mall",
    catagory: "Entertainment",
    rating: 4.00,
    time: 2,
    drive: 5,
    address: "1001 16th St Mall, Denver, CO 80265",
    lat: 39.740959,
    long: -104.985798,
    attributes: ["Drinking", "Dinning", "Shopping"],
    url: "https://www.denver.org/things-to-do/denver-attractions/16th-street-mall/",
    description: "The 16th Street Mall is a pedestrian and transit mall",
    advice: "Eat, Shop, Play on a free bus system",
    img: "https://image.ibb.co/bt2Cv0/16th.jpg",
    start: new Date().toISOString().slice(0, 10)+"T9:30:00",
    time: "9:30:00"
},
{
    name: "little Man Icecream",
    catagory: "Dining",
    rating: 4.00,
    time: 2,
    drive: 5,
    address: "1001 16th St Mall, Denver, CO 80265",
    lat: 39.740959,
    long: -104.985798,
    attributes: ["Drinking", "Dinning", "Shopping"],
    url: "https://www.denver.org/things-to-do/denver-attractions/16th-street-mall/",
    description: "The best icecream spot in a unique area of Denver",
    advice: "Vegan options available!",
    img: "https://image.ibb.co/hfLAhf/littleman.jpg",
    start: new Date().toISOString().slice(0, 10)+"T17:30:00",
    time: "17:30:00"
},
{
    name: "Pearl Street Boulder, CO",
    catagory: "Entertainment",
    rating: 4.00,
    time: 4,
    drive: 45,
    address: "942 Broadway #301, Boulder, CO 80302",
    lat: 40.017112,
    long: -105.279599,
    attributes: ["Drinking", "Dinning", "Shopping"],
    url: "https://www.boulderdowntown.com/",
    description: "The Pearl Street Mall is a four block mall",
    advice: "I highly recomend people watching at Pearl Street.",
    img: "https://image.ibb.co/iudKa0/peal.jpg",
    start: new Date().toISOString().slice(0, 10)+"T09:00:00",
    time: "09:00:00"
},
{
    name: "Flat Irons Boulder, CO",
    catagory: "Adventure",
    rating: 4.00,
    time: 3.5,
    drive: 45,
    address: "Chautauqua Park, Baseline Rd & 9th St, Boulder, CO 80302",
    lat: 53.540974,
    long: -113.368978,
    attributes: ["Hiking", "Nature", "Pictures"],
    url: "https://www.bouldercoloradousa.com/things-to-do/insider-guides/flatirons/",
    description: "Spectacular rock formations in the heart of boulder.",
    advice: "Park at Chautauqua park",
    img: "https://image.ibb.co/jLzsv0/flatirons.png",
    start: new Date().toISOString().slice(0, 10)+"T10:00:00",
    time: "10:00:00"
},
{
    name: "Red Rocks Amphitheater",
    catagory: "Entertainment",
    rating: 4.5,
    time: 2,
    drive: 30,
    address: "18300 W Alameda Pkwy, Morrison, CO 80465",
    lat: 39.667721,
    long: -105.207268,
    attributes: ["Hiking", "Music", "Pictures"],
    url: "https://www.bouldercoloradousa.com/things-to-do/insider-guides/flatirons/",
    description: "Rock structure where concerts are given in the open.",
    advice: "Its free to go anyday, but go early.",
    img: "https://image.ibb.co/jgUgoL/red-rocks.jpg",
    start: new Date().toISOString().slice(0, 10)+"T11:30:00",
    time: "11:30:00"
},
{
    name: "Milk Market",
    catagory: "Dining",
    rating: 3.75,
    time: 1.5,
    drive: 5,
    address: "1800 Wazee St #100, Denver, CO 80202",
    lat: 39.753100,
    long: -104.997260,
    attributes: ["Food", "Shopping", "Pictures"],
    url: "https://www.denvermilkmarket.com/",
    description: "13 restaurant stalls, three bars, and an artisan market.",
    advice: "Check out the ally in the back of the Milk Market!",
    img: "https://image.ibb.co/hMEsv0/milk-market.jpg",
    start: new Date().toISOString().slice(0, 10)+"T18:30:00",
    time: "18:30:00"
},
{
    name: "Denver Botanic Gardens",
    catagory: "Entertainment",
    rating: 3.00,
    time: 2.75,
    drive: 5,
    address: "1007 York St, Denver, CO 80206",
    lat: 39.745080,
    long: -104.959770,
    attributes: ["Pictures", "Shopping", "Learning"],
    url: "https://www.botanicgardens.org/",
    description: "Public botanical garden in the Cheesman Park.",
    advice: "The small fee is worth the experience",
    img: "https://image.ibb.co/ntkXv0/Denver-Botanic-Gardens.jpg",
    start: new Date().toISOString().slice(0, 10)+"T11:00:00",
    time: "11:00:00"
},
{
    name: "Water World",
    catagory: "Entertainment",
    rating: 3.00,
    time: 5.00,
    drive: 5,
    address: "8801 N Pecos St, Federal Heights, CO 80260",
    lat: 39.855901,
    long: -105.00994200,
    attributes: ["Entertainment", "Shopping", "Pictures"],
    url: "https://www.waterworldcolorado.com/",
    description: "Water park that is sure to thrill!",
    advice: "Check the entry times before you go as they change",
    img: "https://image.ibb.co/gM7O2f/water-world.jpg",
    start: new Date().toISOString().slice(0, 10)+"T08:30:00",
    time: "08:30:00"
},
{
    name: "First Ever Chipolte",
    catagory: "Dining",
    rating: 3.25,
    time: 1.00,
    drive: 15,
    address: "1644 E Evans Ave, Denver, CO 80210",
    lat: 39.6782867,
    long: -104.96780360000002,
    attributes: ["Food", "Shopping", "Pictures"],
    url: "https://www.westword.com/restaurants/the-original-chipotle-location-at-1644-west-evans-will-close-for-remodel-on-may-18-2017-9064672",
    description: "Young chef opens burrito joint on East Evans Avenue.",
    advice: "Don't be surpised with how small the location is",
    img: "https://image.ibb.co/bvanTL/chipolte.jpg",
    start: new Date().toISOString().slice(0, 10)+"T11:30:00",
    time: "11:30:00"
},
{
    name: "Illegal Peats",
    catagory: "Dining",
    rating: 3.00,
    time: 1.00,
    drive: 15,
    address: "2001 E Colfax Ave, Denver, CO 80206",
    lat: 39.74024120000001,
    long: -104.96327659999997,
    attributes: ["Food", "Shopping", "Pictures"],
    url: "https://www.illegalpetes.com/",
    description: "Great local borito place. Got to try their fish bowl!",
    advice: "Yummm more borito bowls",
    img: "https://image.ibb.co/dBEsv0/Illegal-Petes.jpg",
    start: new Date().toISOString().slice(0, 10)+"T14:30:00",
    time: "14:30:00"
},
{
    name: "Coors Brewery Tour",
    catagory: "Entertainment",
    rating: 4.00,
    time: 3.00,
    drive: 35,
    address: "13th St & Ford Street, Golden, CO 80401",
    lat: 39.75507899999999,
    long: -105.21793500000001,
    attributes: ["Drinking", "Shopping", "Pictures"],
    url: "https://www.visitgolden.com/places-to-go/coors-brewery-tour/",
    description: "Expansive, renowned brewery offers free tours, as well as tastings.",
    advice: "Check times on website",
    img: "https://image.ibb.co/dr5Xv0/Coors-Brewery.jpg",
    start: new Date().toISOString().slice(0, 10)+"T10:00:00",
    time: "10:00:00"
},
];

db.Events
    .remove({})
    .then(() => db.Events.collection.insertMany(eventSeed))
    .then(data => {
        console.log(data.result.n + " records inserted!");
        process.exit(0);
    })
    .catch(err => {
        console.error(err);
        process.exit(1);
    });